widgets:
    -
            # Where should the widget be placed, left sidebar or right sidebar
            position: left
            type: toc
    
    # Recommendation links widget configurations
    # Table of contents widget configurations
    -
        position: right
        type: latest_comment
#    -
#        # Where should the widget be placed, left sidebar or right sidebar
#        position: left
#        type: links
#        # Names and URLs of the sites
#        links:
#            Hexo: 'https://hexo.io'
#            Bulma: 'https://bulma.io'
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: categories
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives